### ISSUE TITLE
Inference Scoring

### ISSUE THREAD

**Issue by Sentdex** [daniel-kukiela/nmt-chatbot#1]
Thought we could start a project around the inference choices/scoring. 

At the moment, there are 3 tiers (-1, 0, or 1). I think we should have a larger range, and I would like to start with some ideas here for that. 

1. Finished thoughts/sentences OR is complete URL. From what I have seen so far, if the AI doesn't end a sentence with some ending punctuation, it's a problem

2. Penalize repetition. Example: "I don't know what you're talking about, but I don't know what you're talking about." 

3. Penalize parroting: When his response to a question is basically either just repeating the question, or something very close to that. Example:

> ______________________________
> > Legalize medical marijuana in 2 0 0 1 too ! Just goes to show how forward thinking this guy is .
> 
> Reply: legalize marijuana in 2 0 0 1
> ______________________________

or..

> ______________________________
> > I like the idea ... have an upvote !
> 
> Reply: I like the idea .
> ______________________________

or...

> 
> ______________________________
> > Why am I so nervous ?
> 
> Reply: Why am I nervous ?
> ______________________________
>

**Comment by kunwar31** [comment]
[https://github.com/daniel-kukiela/nmt-chatbot/pull/5](url) 
What do you think about this?
