### ISSUE TITLE
Tensorflow version must >= 1.4.0

### ISSUE THREAD

**Issue by ahmedmn** [daniel-kukiela/nmt-chatbot#104]
Hi Daniel,

I'm trying to run train.py, I'm receiving the following error, however I have the updated tensorflow
I did run " pip install --upgrade tensorflow"

Any suggestions?

```
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from nmt import nmt
  File "C:\chatbot\nmt-chatbot/nmt\nmt\nmt.py", line 28, in <module>
    from . import inference
  File "C:\chatbot\nmt-chatbot/nmt\nmt\inference.py", line 24, in <module>
    from . import attention_model
  File "C:\chatbot\nmt-chatbot/nmt\nmt\attention_model.py", line 22, in <module>
    from . import model
  File "C:\chatbot\nmt-chatbot/nmt\nmt\model.py", line 31, in <module>
    utils.check_tensorflow_version()
  File "C:\chatbot\nmt-chatbot/nmt\nmt\utils\misc_utils.py", line 34, in check_tensorflow_version
    raise EnvironmentError("Tensorflow version must >= %s" % min_tf_version)
OSError: Tensorflow version must >= 1.4.0
```
Thanks
Ahmed

**Comment by ahmedmn** [comment]
pip install tensorflow=1.4.0

**Comment by daniel-kukiela** [comment]
I recently fixed that issue.
Are you using my recent fork of NMT?

**Comment by ahmedmn** [comment]
Yes, I do. Now I'm running the training and it works well, thanks!

**Comment by daniel-kukiela** [comment]
Thanks for a feedback :)

**Comment by anonmanx** [comment]
Daniel,I was following sentdexe's tutorial and if I don't clone the branch v0(probably) I don't find a inference.py file there and that played a great part in the tutorial.So I'm just using your older version but aI ahve thensorflow-gpu 1.12.0 and when I run train.py,that throws the same error as above.What to do ?Cuz,without inference.py file or specifically those inference files how can I interact with the chatbot?
