### ISSUE TITLE
want to have my own train test data

### ISSUE THREAD

**Issue by jackyclever** [daniel-kukiela/nmt-chatbot#11]
Hi all, can i remove/delete tst2012.(from|to)m tst2013(from|to)) completely, as i just have tran/test/.from/.to files.

i have errors when i tried to remove them :(

**Comment by daniel-kukiela** [comment]
Short answer - you can't. Why would you even want to do that?

**Comment by jackyclever** [comment]
Hi Kukiela:

Thank you for your reply, as i want to use my own training/testing set completely, so try to remove tst2012/2013. or otherwise can i empty those two files?

another question i have is: does the training model supports incremental training? like i train it half way and stop, can i retrain it? or it will starting from beginning again?

and can i use the same model to train other languages like french or chinese?



Regards

Jacky

On 9/12/2017, at 8:19 PM, Daniel Kukieła <notifications@github.com<mailto:notifications@github.com>> wrote:


Short answer - you can't. Why would you even want to do that?

**Comment by daniel-kukiela** [comment]
If you want to use your training set, you should make own tst2012/2013 files. If you didn't see, take a look: https://www.youtube.com/watch?v=dvOnYLDg8_Y.

You can stop and restart training. Checkpoint is saved every 1000 steps, but progress with training set every 5000 steps, so you should stop training just after nearest 5000 streps.

You can use that model for other languages, but you probably want to look ate "txt" files inside "steup" folder.
