### ISSUE TITLE
Chatbot training output issue

### ISSUE THREAD

**Issue by GauthamPughaz** [daniel-kukiela/nmt-chatbot#12]
Hi Daniel, I have a issue regarding about my output in out_dev file, the model produces responses as [ deleted ] for most samples that are logged in my out_dev file and I also had attached my out_dev file and tensorboard screenshots. Its been 34000 steps and still its the same for nearly all samples. Am I  going wrong or do I need to stop the model? I am using following params:
1. num_units: 512
2. num_layers: 2
3. vocab_size: 100000
Thank you

![out_dev1](https://user-images.githubusercontent.com/11377638/33848511-fea4c7f8-ded3-11e7-84c1-3a92b4613a2e.png)
![out_dev2](https://user-images.githubusercontent.com/11377638/33848512-fee30bda-ded3-11e7-95db-8846b4af2e09.png)

![tensorboard](https://user-images.githubusercontent.com/11377638/33848515-ff6b01a2-ded3-11e7-8142-c2a40ed6c097.png)

**Comment by daniel-kukiela** [comment]
I'm curious why you are getting '[deleted]' in your output files. What's the source of your corpus?
Did you prepare data using setup/prepare_data.py?
I had such a problem once, when i used vocab file from diffrent training set, by a mistake.
Please make a screenshot of top entities of your vocab file, and tell more about training set.

**Comment by GauthamPughaz** [comment]
Yes, I ran setup/prepare_data.py. I use reddit corpus of 2015-01 and the number of trianing pairs is 3.14M. In my new_data folder the train.from and train.to are from 2015-01 reddit corpus but I did not change tst2012.from, tst2013.from, tst2013.to and tst2012.to files in that directory. Is that the issue? 

![console](https://user-images.githubusercontent.com/11377638/33872393-b95b7a0c-df3c-11e7-9c23-69269c68eae1.png)
![vocab_from](https://user-images.githubusercontent.com/11377638/33872455-fd1ac644-df3c-11e7-8eed-bb023533fd33.png)

**Comment by Sentdex** [comment]
Are you doing regular hidden layers or bi-directional?

**Comment by GauthamPughaz** [comment]
My encoder type is bi-directional because I didn't comment 'encoder_type': 'bi' in my settings.py. Unfortunately as you said I made a logical error while preparing my database, so [deleted] was included in my database. I think that was the cause of [deleted], though I have attached the required screenshots.
Also Can I know what 'num_units', 'num_layers', 'vocab_size' values will you use for NVIDIA TESLA K80
GPU with 12GB of DDR5 memory?

Thank you..

![tst2013_to](https://user-images.githubusercontent.com/11377638/33932192-49f07ff0-e018-11e7-9b02-bb58ce118ee9.png)
![tst2013_from](https://user-images.githubusercontent.com/11377638/33932194-4a444e6e-e018-11e7-96fc-3a7c5375f9b0.png)
![train_to](https://user-images.githubusercontent.com/11377638/33932195-4a80a0c6-e018-11e7-94dc-4c53fd02d5d0.png)
![train_from](https://user-images.githubusercontent.com/11377638/33932197-4b067df4-e018-11e7-9dce-406d79ed4a07.png)

**Comment by daniel-kukiela** [comment]
Everything looks pretty normal, so i'm even more curious why you are getting such a results.
Are you able to pack/compress files (whole 'nmt-chatbot' folder) using tool of your choice and provide some download link with me? I would like to check that.
