### ISSUE TITLE
Bleu_rate 0.00

### ISSUE THREAD

**Issue by danielissac** [daniel-kukiela/nmt-chatbot#120]
Bleu_rate is still 0.00 even after the global step 2000 is that normal? Should I restart?
I've changed the batch size from 128 to 64 and set the override_loaded_hparams = True.

**Comment by andrewdoud** [comment]
Hi there, have been having this problem as well, did you figure out a way to solve this issue? My bleu has been zero for 70k steps.

**Comment by andrewdoud** [comment]
I found in separate threads that:
    1. Many people's bleu scores don't go up until after ~100k steps
    2. When training a massive set of data bleu will often be very low because of high variance in 
        responses, and thus is not actually that important of a metric.
