### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Johk3** [daniel-kukiela/nmt-chatbot#121]
It seems like for some reason the tensorflow-gpu is looking for libcublas.so.9.0 which doesnt exist in cuda 9.1 that I have on my system. 
Would there be anyway around this?

**Comment by benonilearns** [comment]
You can create an anaconda environments and install tensorflow-gpu. It will install those it self.

conda create -n tensorflowgpu python=3.6
conda activate tensorflowgpu
conda install tensorflow-gpu

then go to the requirements text and install everything except tensorflow-gpu==1.4.0 with pip by hand.
