### ISSUE TITLE
Where does <unk> come from?

### ISSUE THREAD

**Issue by benni93** [daniel-kukiela/nmt-chatbot#13]
I´m training my chatbot right now and read some of the results in the training terminal.
<unk> appears very often. It's not in the training data but it is in the vocabs. Why is it added there?

**Comment by daniel-kukiela** [comment]
`<unk>` is one of the three special tokens. It basically means what you think - 'unknown'. The purpose for that token is to replace every entity in training that doesn't exist in vocab. Same for inference (when you are "asking" AI).
So every entity that is not included in vocab will be replaced with `<unk>` and AI will respond with sentences that are including `<unk>`s. To lower number of that tokens with responses you have to include more entities in vocab files (make "bigger" vocab files.
Also, if you are training your model, you will see a lot of `<unk>`s. Later you should see them less and less the further in training process.

**Comment by benni93** [comment]
Thank you!
With the standard settings, how high can I go with vocab size using 8GB VRAM?

**Comment by daniel-kukiela** [comment]
Standard settings are tuned for 4GB of VRAM, so just try to raise 'vocab_size' as much as possible. If you would like to raise it further, you have some possibilities to free some VRAM memory (in exchange for overall model abilities), you can:
- change 'num_units' to 256
- uncomment and change 'batch_size' to 64
- comment out 'encoder_type'
But it's hard to tell how model will change - you will have to train couple of them using diffrent settings and compare results.

**Comment by benni93** [comment]
FYI: vocab size = 100k is not working, 75k is working
