### ISSUE TITLE
tst2012(from/to) and tst2013(from/to)

### ISSUE THREAD

**Issue by umangkr** [daniel-kukiela/nmt-chatbot#14]
I replaced everything in new_data dir.
Run the prepare.py.
Created the vocab successfully..
But when running it throws an error..
The image file is attached
![screenshot 14](https://user-images.githubusercontent.com/30562064/34036288-b9730300-e1aa-11e7-90ae-54595ff257ac.png)

**Comment by daniel-kukiela** [comment]
Are there any files inside `H:\chatbot\nmt-chatbot\data\` folder? And if yes, what files do you have there?

**Comment by umangkr** [comment]
The new_data folder
![20171215_195918](https://user-images.githubusercontent.com/30562064/34046304-976705ea-e1d2-11e7-94e4-3466df2c1500.png)



The data folder
![20171215_195730](https://user-images.githubusercontent.com/30562064/34046321-aaf77964-e1d2-11e7-9248-ec0ffb20d3aa.png)

**Comment by daniel-kukiela** [comment]
Error message says `H:\chatbot\nmt-chatbot\data\` not `D:\nmt\data`, so i'm confused now.

**Comment by umangkr** [comment]
I thought it might have not cloned properly..
So i again cloned it in different drive (D:\nmt) 
But again it threw the same error.

**Comment by daniel-kukiela** [comment]
But error says about H: drive, how?

**Comment by umangkr** [comment]
Cause that screenshot was taken when i had it in (H:) drive and i raised the issue here that time..
After posting here i cloned the project again but this time in drive(D:). 

Hope i am clear now.

**Comment by daniel-kukiela** [comment]
Ok, now i can see the issue - code expects tst2012 and tst2013 files, and there are no such a files in your training set. Update `hparams` section of `setup/settings.py` with correct filenames.
Also read README in GitHub - you can't paste files directly into `data` folder !!

**Comment by umangkr** [comment]
I did not paste any files in the data folder.
It was all there after i ran the prepare.py

I only pasted the files in new_data folder

**Comment by umangkr** [comment]
And also i did what you told me..
I changed the file names correctly..
But again its throwing the same error

**Comment by daniel-kukiela** [comment]
`setup/prepare_data.py` is unable to create those files i can see in your screenshot. It produces files with strict names. So at least tst2007-tst2011 files are pasted by hand.
Even `setup/prepare_data.py` itself shouldn't complete successfully, as there were no correct files for it to prepare full training set.

Remove everything, start fresh, prepare correct data set consisting of files: train.(from|to), tst2012.(from|to), tst2013.(from|to) and do everything step by step as written in README.

**Comment by umangkr** [comment]
Okay..
I will do it.
And let you know
