### ISSUE TITLE
Update for tensorflow 2.0?

### ISSUE THREAD

**Issue by danielriddell21** [daniel-kukiela/nmt-chatbot#144]
Is there a way this could be updated for tensorflow 2.0? Either by me doing it or by the repo being updated.

Alongside that, what are the benefits of 2.0

**Comment by SkullEnemyX** [comment]
Please help, even I want to run it on tensorflow 2.0.1. Help asap. Either code can be changed or how to install tensorflow from scratch asap.

**Comment by kaljitism** [comment]
Facing the same issue, running on AWS is impossible with tf-gpu because cuda is preinstalled.

**Comment by kaljitism** [comment]
And Cuda version is higher than what 1.12 or 1.4 uses.

**Comment by Jay-ArBrouillard** [comment]
I went through a couple of days of gather data to realize it doesn't work for Tensorflow 2....

**Comment by danielriddell21** [comment]
Does not support Tensorflow 2.0
