### ISSUE TITLE
ImportError in train.py

### ISSUE THREAD

**Issue by prbhtkumr** [daniel-kukiela/nmt-chatbot#152]
`ImportError: cannot import name 'nmt' from 'nmt' (unknown location)` ,

I've tried this on both, Linux and Windows 
getting the same error :/

**Comment by dusty-dusty** [comment]
Go to https://github.com/daniel-kukiela/nmt/tree/33acea2284a2d719773d73fdd8e751e4ce734dfe and clone nmt from here, then copy and paste it into the main folder

**Comment by 01010000-kumar** [comment]
> Go to https://github.com/daniel-kukiela/nmt/tree/33acea2284a2d719773d73fdd8e751e4ce734dfe and clone nmt from here, then copy and paste it into the main folder

what main folder?

**Comment by kaljitism** [comment]
Dont forget to use 'recursive' tag while cloning the repository
