### ISSUE TITLE
Prepare_data UnboundLocalError

### ISSUE THREAD

**Issue by sebasyii** [daniel-kukiela/nmt-chatbot#154]
I am experiencing an UnboundLocalError. I'm not sure how I can fix this.

```Preparing training set from raw set
File: train.from
Traceback (most recent call last):
  File "prepare_data.py", line 563, in <module>
    prepare()
  File "prepare_data.py", line 79, in prepare
    number_of_records = min(amount, sum(1 for _ in open_function(source_file_name, 'rt', encoding='utf-8', **additioan_params)))
UnboundLocalError: local variable 'open_function' referenced before assignment```

**Comment by kobrata6** [comment]
Hello! I see that you closed this. Can you tell me how you fixed it? Thanks!

**Comment by sebasyii** [comment]
Hi! If I remember correctly, I changed the name of train.from file, which is why it prompt me that error.

**Comment by kobrata6** [comment]
Eh I changed it and still have the same problem. Do you mean the train.from file in data folder?

**Comment by sebasyii** [comment]
the train.from file from the new_data folder.
