### ISSUE TITLE
UnboundLocalError: local variable 'open_function' referenced before assignment

### ISSUE THREAD

**Issue by kobrata6** [daniel-kukiela/nmt-chatbot#157]
This is what i get when i try to run the prepare_data.py in Terminal of Ubuntu 18.04. 
 `dani@dani-Latitude:~/nmt-chatbot/setup$ python3 prepare_data.py
Preparing training set from raw set
File: train.from
Traceback (most recent call last):
  File "prepare_data.py", line 565, in <module>
    prepare()
  File "prepare_data.py", line 80, in prepare
    number_of_records = min(amount, sum(1 for _ in open_function(source_file_name, 'rt', encoding='utf-8', **additioan_params)))
UnboundLocalError: local variable 'open_function' referenced before assignment
`
In my new_data folder i have put my files with data. Is this the problem?
I tried to change the name of train.from file, but it did not work. Any possible solutions?

**Comment by Nathan-Chell** [comment]
Id start up a VM and freshly install everything

**Comment by kobrata6** [comment]
> Id start up a VM and freshly install everything

I am doing it on ubuntu 18.04 I do not need VM + I installed everything freshly

**Comment by kobrata6** [comment]
Okay - to sum up, the problem was that i have downloaded pip requirements and not pip3, so use pip3 and python3 and everything is fine
