### ISSUE TITLE
Doubt regarding scoring function

### ISSUE THREAD

**Issue by imshashwataggarwal** [daniel-kukiela/nmt-chatbot#16]
Shouldn't the score be summed rather than assignment at each step of this function, since currently it takes score from bad response function only.

https://github.com/daniel-kukiela/nmt-chatbot/blob/524b22fb7e8524fbaa3b0be2f21cb94c314774ca/sentdex_lab/scoring.py#L158-L167

Thanks,
Shashwat Aggarwal

**Comment by daniel-kukiela** [comment]
Every function takes previous score as a parameter, and returns a new score that is based on previous one, so... no, it shouldn't :)

**Comment by imshashwataggarwal** [comment]
Oh my bad. Thanks btw! :)
