### ISSUE TITLE
how can I use it without an NVIDIA GPU?

### ISSUE THREAD

**Issue by j4rv1s1** [daniel-kukiela/nmt-chatbot#17]
Hi i'm following the video tutorial of Sentdex https://www.youtube.com/watch?v=040CfFRJ9Rs&t=418s
but I don't have an nvidia gpu, how can i train my model "train.from" and "train.to" using a cpu? what do i need to download? I see he uses python scripts in this github project. but how can i do? where do i find these python scripts in order to train my models? :)

**Comment by daniel-kukiela** [comment]
Install cpu version of Tensorflow:
- pip uninstall tensorflow-gpu
- pip install tensorflow
That's all.

I don;t quite understand second part of your question. You're here, asking questions, so you're at right place to download a code, everything's in README. Just click 'Code' above.

**Comment by j4rv1s1** [comment]
so wait, you are telling me i can use the python scripts of this github repo simply installing the cpu version of tensorflow instead of using the gpu version? :)

**Comment by daniel-kukiela** [comment]
Correct :)
