### ISSUE TITLE
Path to trained files, checkpoint, etc passed by an argument

### ISSUE THREAD

**Issue by binksdata** [daniel-kukiela/nmt-chatbot#18]
Can we please have a path to trained files 
translate.ckpt-76000.data-00000-of-00001*.* etc
passed as an argument to the inference.py
Thanks!

**Comment by daniel-kukiela** [comment]
I think that's a good idea.

As a workaround you can edit `model/checkpoint` file.

I'm not sure how did you get filename like that.

**Comment by binksdata** [comment]
Yes, editing the checkpoint file works. That name is like names from Sentdex tutorial, look quite similar.

https://pythonprogramming.net/interacting-chatbot-deep-learning-python-tensorflow/

"checkpoint
translate.ckpt-225000.meta
translate.ckpt-225000.index
translate.ckpt-225000.data-00000-of-00001
"

**Comment by daniel-kukiela** [comment]
I've added ability to pass checkpoint name as an argument, for example:

    python inference.py translate.ckpt-1000

I'll add deployment script as well soon (it's almost redy) prepairing model for deployment including ability to choose model (it will save all necessary files to run inference in separate folder).

**Comment by daniel-kukiela** [comment]
Deployment utility added to repository.
