### ISSUE TITLE
How would I import inference.py to use with another script like a discord app.

### ISSUE THREAD

**Issue by rhaejr** [daniel-kukiela/nmt-chatbot#19]
Just sitting here trying to figure out if I can import inference and what to call from it to get responses for my discord bot. I would imagine I would need to make something similar to everything below if __name__ == "__main__":. But I am trying to sort through it and I'm just getting all confused.

**Comment by daniel-kukiela** [comment]
That info is already included at the bottom of README: https://github.com/daniel-kukiela/nmt-chatbot/blob/master/README.md#importing-nmt-chatbot

**Comment by rhaejr** [comment]
I am sorry I missed that part somehow. Thanks.
