### ISSUE TITLE
prepare_data.py UnboundLocalError: local variable 'last' referenced before assignment

### ISSUE THREAD

**Issue by benni93** [daniel-kukiela/nmt-chatbot#2]
I get the following error:

> File: train.from (iteration = 10k lines)
> 1it [00:00,  4.19it/s]Exception in thread Thread-7:
> Traceback (most recent call last):
>   File "C:\xxx\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\xxx\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "prepare_data.py", line 155, in write_lines
>     file.write('\n'.join(lines) + ('' if last else '\n'))
> UnboundLocalError: local variable 'last' referenced before assignment

Indeed, "last" gets first assigned in the if conditional:

>     if not len(lines) or lines[-1] == '':
>         lines = list(filter(None, list(lines)))
>         last = True

**Comment by kunwar31** [comment]
You need to initialize last to False in function write_lines

**Comment by daniel-kukiela** [comment]
Thank you @benni93 and @kunwar31 
Fixed by #3

**Comment by daniel-kukiela** [comment]
close
