### ISSUE TITLE
Link to download the trained modelcheckpoint

### ISSUE THREAD

**Issue by PotatoSpudowski** [daniel-kukiela/nmt-chatbot#21]
Hey can we please have the link to the trained model checkpoint?
pretty please!!!

**Comment by daniel-kukiela** [comment]
I could train some model uging example data. For now we are busy doing something else, and i have a big code update, that adds a new feature.

What exactly would you like to be able to download? How well trained model, what data should be used for training?

**Comment by PotatoSpudowski** [comment]
A good enough model that I could have basic conversation with. I just want to play around and have fun :P

**Comment by vinpalace** [comment]
Any estimate on how long your training would take ? :)

**Comment by daniel-kukiela** [comment]
I am training some production model right now.
I'll try to spin some machine to train some other model for you during that weekend.

**Comment by daniel-kukiela** [comment]
Please use https://github.com/daniel-kukiela/nmt-chatbot/issues/29 for further informations.

**Comment by vinpalace** [comment]
Thank you very much. I'm using this as a part of my project and my training
seems to take forever and bleu score is stuck at 0.00. Was not able to fix
it

**Comment by heyseth** [comment]
@daniel-kukiela Sooo... any links to a trained model? Would really appreciate it :)

**Comment by heyseth** [comment]
@daniel-kukiela Hey, I'm not sure if you missed my earlier comment, but I would be seriously grateful if you could share a trained model :-)

I understand if that's too much of a hassle, or if you have other reasons not to share, but I figured it's worth a shot.

**Comment by sleepycode** [comment]
any idea when you'd upload it?

**Comment by daniel-kukiela** [comment]
I am going to train some small model right now. I'm going to use GTX 970 for that (4 GB of VRAM), so model won't be big, but you should be able to use it as a sample bot.

**Comment by sleepycode** [comment]
thank you so much.

**Comment by daniel-kukiela** [comment]
Model finished second epoch of training. Two more.

**Comment by daniel-kukiela** [comment]
Model is trained for four epochs now, needs one probably.

**Comment by daniel-kukiela** [comment]
Demo chatbot: https://github.com/daniel-kukiela/nmt-chatbot#demo-chatbot

**Comment by heyseth** [comment]
@daniel-kukiela Thank you so much! Can't wait to give it a spin :-)

Btw: it appears the link is commented out in the markdown, not sure if this is intentional.

**Comment by daniel-kukiela** [comment]
Interesting, PyCharm plugin didn't show me that mistake. Fixed. Thank you fo info.

**Comment by tolotrasamuel** [comment]
@daniel-kukiela  What was your step-time using the GTX 970 of (4 GB of VRAM) ? I want to benchmark it with mine ( a GTX 1060 6 GB of VRAM) I feel like there is something wrong with mine because it is very slow. (around 12 s per step )

**Comment by daniel-kukiela** [comment]
It's relatively small model. Something around 1s.
How long are your sentences (in number of chars)?

**Comment by daniel-kukiela** [comment]
If you want to talk about step times, maybe let's move to a new issue, or the one you already opened.

**Comment by neeraj26jan** [comment]
> Demo chatbot: https://github.com/daniel-kukiela/nmt-chatbot#demo-chatbot
> 
> Please keep in mind it's very small model, not any decent. I will train bigger one in some time for sure, but if you look at amount of time it took me to be able to train that one... it will take some time.

Hi Daliel,
Can you provide some bigger and cleaner trained model just for general chit-chat? My email id is neeraj.26jan@gmai.com. If you can share the trained model over google drive, it would be great. Thanks a lot.
