### ISSUE TITLE
CPU only support

### ISSUE THREAD

**Issue by Phantast** [daniel-kukiela/nmt-chatbot#25]
I'm wondering if the chatbot could be trained with a CPU only.
I have an AMD GPU and therefore cannot run tensorflow, as it only supports NVIDIA GPUs.
Does it even make sense to train with a CPU, or would it take so much longer that I'll have to let my grandchildren check for the results? :) 
I followed the Chatbot tutorial and just reached this point, so it would be great if there is a way to use CPU only. Even if it does not make sense to train on large datasets, but just to experiment with it.
Thanks for the great tutorial and the chatbot on github!

**Comment by daniel-kukiela** [comment]
All you have to do is:
- `pip uninstall tensorflow-gpu`
- `pip install tensorflow`

Training using CPU is ~20x slower than using GPU. You probably won't train a decent model in reasonable time, but it's worth to try anyway.

**Comment by Phantast** [comment]
Thanks! Works fine. 
Did not expect it would be that easy. Thought there would be many more dependencies.
