### ISSUE TITLE
ImportError: No module named HTML

### ISSUE THREAD

**Issue by JleanderS** [daniel-kukiela/nmt-chatbot#26]
nmt-chatbot/setup$ python prepare_data.py
Traceback (most recent call last):
  File "prepare_data.py", line 8, in <module>
    from core.tokenizer import tokenize
  File "../core/tokenizer.py", line 1, in <module>
    import HTML

How to fix? :(

**Comment by Hyperclaw79** [comment]
It should be `import html` Case sensitive.

**Comment by JleanderS** [comment]
Same Error again only just html instead of HTML

**Comment by Hyperclaw79** [comment]
Can you post the entire traceback along with the actual error message and your Py and tf versions?
Use `python --version` and `pip freeze` (for modules listed in the requirements.txt).

**Comment by KodeyThomas** [comment]
`sudo apt-get install html` should work

**Comment by sunnysaxena** [comment]
works fine for me with **pip install html** in virtual environment
