### ISSUE TITLE
can you please provide a pretrained model? your trained model.

### ISSUE THREAD

**Issue by sleepycode** [daniel-kukiela/nmt-chatbot#29]
it would be really great if i could see your trained model as my gtx850m 4gb takes forever to train the model.
i have no intention of using your model for any purpose over the internet.

**Comment by daniel-kukiela** [comment]
There is already issue for that - #21 
Please subscribe to the issue mentioned above. I'll provide some trained model.
I was training models using GTX 970 ($GB of VRAM as well) and yes, it takes time to train decent model :)
