### ISSUE TITLE
Training new data while retaining current progress

### ISSUE THREAD

**Issue by ChorusJX** [daniel-kukiela/nmt-chatbot#30]
Hi, is it possible to train on new set of data and retain the current trained progress?
If it is possible, how should i go about doing it?

Thank you for your help, as i am still very new to this i would like to apologize if this is a stupid question.

**Comment by daniel-kukiela** [comment]
Should be possible in theory.
It's build on top of NMT, i'm not sure how NMT will handle change like this.
If you want to try:
1. stop training
2. place new corpus inside new_data fodler replacing existing files (use the same names)
3. run `setup/prepare_data.py`
4. run `train.py` again
In case of any problems you might try to set `override_loaded_hparams` inside `hparams` section of `setup/settings.py` file before restarting train process (but only for the first time).


Regards,
Daniel

**Comment by ChorusJX** [comment]
Okay sure,

Will try it out. Thanks Daniel!

Regards,
JX
