### ISSUE TITLE
Increasing the vocab size

### ISSUE THREAD

**Issue by VariyaKrupal** [daniel-kukiela/nmt-chatbot#35]
I am currently on step 31K, vocab = 25000 

want to increase vocab to 50000 now. Should I change vocab size in settings.py and run prepare_data.py again followed by train.py to continue from step 31K??﻿

**Comment by daniel-kukiela** [comment]
You really shouldn't change that unless you really know what you are doing.

You probably can try to increase vocab, but you have to be absolutely sure that all existing tokens will stay at their current positions. I didn't do that before tho, i'm not sure about the results.
