### ISSUE TITLE
In the first step itself I'm getting this error.

### ISSUE THREAD

**Issue by MLguy07** [daniel-kukiela/nmt-chatbot#36]
git clone --recursive https://github.com/daniel-kukiela/nmt-chatbot/tree/v0.1
Cloning into 'v0.1'...
remote: Not Found
fatal: repository 'https://github.com/daniel-kukiela/nmt-chatbot/tree/v0.1/' not found

**Comment by daniel-kukiela** [comment]
Proper usage:
`git clone --branch v0.1 https://github.com/daniel-kukiela/nmt-chatbot.git`
I will fix that in README
