### ISSUE TITLE
Moving the chatbot around

### ISSUE THREAD

**Issue by ZafirStojanovski** [daniel-kukiela/nmt-chatbot#38]
Okay, I've done a little training of the chatbot, and I tried moving it around my folders structure, but it seems that it takes the physical paths for some of the dirs. Found out that hparams is one of the folders that holds the physical paths. Which other folders need to be modified in order to be able to run the model from anywhere?
Also, what are the minimum files to run the inference script?

**Comment by daniel-kukiela** [comment]
The other file is `checkpoint` in same directory.
It's an issue of NMT itself, we are not saving absolute path anywhere.
Anyway i'm going to write some toll that will set those paths correctly, maybe even check and correct them on runtime. I'm working on some changes in chatbot now, so maybe i'll add that soon.

Minimal version:
- `data` - `bpe_joins.common.json` if you are using BPE/WPM-like tokenizer, vocab file (name depends on settings)
- `model` - you may reduce it to just the one checkpoint you want to use (remember to edit `checkpoints` file accordingly), so let's say you like checkpoint after 130000 steps - leave `best_bleu`, `translate.ckpt-130000.*`, `checkpoint` and `hparams`, edit `checkpoints` and set that checkpoint there
- `new_data` - unnecessary
You shlould leave other folders untouched (you don;t need `tests` folder for example, but is there any reason to remove that?)

**Comment by daniel-kukiela** [comment]
There are new changes in repository.
One of the changes fixed paths in model. Starting from now model can be easly moved around between different folders, machines or even operating systems.

Deplyment script is still in `work in progress` state, should be available soon (probably tomorrow).

**Comment by daniel-kukiela** [comment]
Deployment utility added to repository.
