### ISSUE TITLE
Question on adding tags to training data

### ISSUE THREAD

**Issue by spiderwisp** [daniel-kukiela/nmt-chatbot#43]
So while observing some bots training and fiddling around a bit, one thing I would like to do is add tags to the training data. Something like this `Hi, my name is [FIRSTNAME] from [UNIVERSITY], nice to meet you. Today is [DAYOFWEEK].`

Then I could use the tags to dynamically customize bots using the same training data.

Using brackets like this seems to work as the brackets and containing text does get output after training. But, I'm wondering if there is a better way to implement this tagging behavior.

**Comment by spiderwisp** [comment]
Sorry for all the questions, but I'm also curious about the order of the data in the `train.to` and `train.from` files.

Since this is a regressive neural network (hope I got that right) the data is fed back into it (if I understand properly), so does that mean if I want to feed a dialog in that the order matters?

For example if I had a conversation like:
Q: Hello
A: Hi there, how are you today
Q I'm well, but this rain is terrible
A: Sorry to hear that
Q: I wish it would stop
A: Soon the rain will stop

Does it help to main the order of this conversation in the training files?

Many thanks for the help.

**Comment by daniel-kukiela** [comment]
Tags - that's probably the best way to do that. The only thing you can do is tu add those tags to protected phrases (inside setup folder). That file is a list of regexes, so add it like that (probably): `(\[some_tag\])`

This is model used to translate phrases between language. We are using it to translate from Engglish to... English. Training corpus consists of pairs of input and output phrases neural network learns. So yes, the order matters. You have to split that between `from` (Q) and `to` (a) files keeping the right order.
