### ISSUE TITLE
Update recursive NMT to look for newer versions of CUDA

### ISSUE THREAD

**Issue by jf0772256** [daniel-kukiela/nmt-chatbot#49]
Vurrently your version of NMT requires a specific version of CUDA v9.0 I have 9.1 installed and in order to run train.py I have had to roll back CUDA to 9.0 This is annoying.

I dont foresee that the issue of versioning should be too terribly had to do I only ask that you look into making it more forward compatible for future users.

**Comment by daniel-kukiela** [comment]
I think you are using Windows - Windows binaries of Tensorflow are compiled against CUDA 9.0 and cuDNN 7.0. If you want to use CUDA 9.1 and cuDNN 7.1 you have to compile Tensorflow by yourself. Your issue is not related to NMT or anything done here.

**Comment by jf0772256** [comment]
Yes thank you.
