### ISSUE TITLE
Problems With Importing NMT

### ISSUE THREAD

**Issue by cripplingcancer** [daniel-kukiela/nmt-chatbot#51]
I've trained all the chat data and ran almost everything, except python won't import nmt at all, i have no idea what to do here, please help me out.

**Comment by daniel-kukiela** [comment]
Did you pull repo recursively (as written in readme)?

If yes, can you post full traceback with error message?

**Comment by cripplingcancer** [comment]
i dont think i pulled recursively, but i did run the requirements installer


Traceback (most recent call last):
  File "C:\Users\austi\Desktop\nmt-chatbot-master\train.py", line 8, in <module>
    from nmt import nmt
ImportError: cannot import name 'nmt'


this is the "train.py" file that came with the download (not pulled from GitHub in python).

**Comment by daniel-kukiela** [comment]
Like i said, you have to pull recursively, it's in readme.
