### ISSUE TITLE
What all changes do I need to make if I need to develop the chatbot using MySQL instead of SqLite

### ISSUE THREAD

**Issue by shresthpaul133** [daniel-kukiela/nmt-chatbot#52]
I need to create a chatbot which has the custom database. So I just wanted to know what all changes do I need to make to create the chatbot. Provided that I'm using the same set of data entries in the database.

**Comment by daniel-kukiela** [comment]
This project doesn't use sqlite, so i'm not sure what you mean by that.

Also we are using Google NMT that requires training dataset to be saved in text files, not in a database.

Can you say more about what are you going to achive?

**Comment by shresthpaul133** [comment]
@daniel-kukiela  Sir I have to create a chatbot using mysql so that we can insert our own data, into the database. Like you were using reddit database. Similarly I don't want to use that. I want to use my own database.

**Comment by daniel-kukiela** [comment]
Did you see that @Sentdex 's tutorial: https://pythonprogramming.net/building-database-chatbot-deep-learning-python-tensorflow/ ?
What you have to do is to make own train files - source and target ones. You don;t even need to use any database engine. You have sample files attached in `new_data` folder.
I'm not really sure how i can help you.

**Comment by shresthpaul133** [comment]
@daniel-kukiela Sir, what I've to do is:- Company is having it's own messenger but they want me to build a chatbot just like yours. It will contain all the data like all the commands that are to be used in the company so that employees will be at ease. That's what our main aim is. So I need to create a database on my own. That database will contain every command that we normally use, even those which we don't mostly use. So how do I do that ?
