### ISSUE TITLE
Problem in prepare_data.py

### ISSUE THREAD

**Issue by mcnoob88** [daniel-kukiela/nmt-chatbot#53]
Hi , I came into this error when i run prepare_data.py from cmd:

Traceback (most recent call last):
File "prepare_data.py", line 5, in <module>
    from core.tokenizer import tokenize
ModuleNotFoundError: No module named 'core'

The error did not came out when I run it from python and is it normal to get this respond when training the chatbot:
src: ▁> ▁O ld ▁M a us ers ▁newlinechar ▁newlinechar ▁FTFY
    ref: ▁Two ▁of ▁them ▁are ▁definitely ▁beat ers ! ▁LOL !
    nmt: > Old Mausers newlinechar newlinechar FTFY

The underscore does not appear in the older version and I am using the latest nmt-chatbot.

**Comment by tonythefreedom** [comment]
I have the same issue

**Comment by daniel-kukiela** [comment]
Hi.

Are you sure you are using latest version of code? I was using `prepare_data.py` a lot lately in many ways without any issue.
Did you modify files or folder structure in any way?

As for underscores - something is odd here - underscores shouldn't be printed. Did you get that repo recursively (it will include our modified fork of `nmt`)?

**Comment by mcnoob88** [comment]
I didn't get that repo recursively by the first way. Now I had get it recursively and the underscore is gone but I still can't get prepare_data.py running from Git Bash and cmd. I am running prepare_data.py from python and everything seems working normally. Thanks by the way.

**Comment by daniel-kukiela** [comment]
Underscores - yes, it's related but not that exactly. NMT is modified by us and includes some fixes.

I'm not really sure what do you mean by run `prepare_data.py` in GitBash or in Python. Can you please show me screenshots of all those 3 ways?

**Comment by mcnoob88** [comment]
Here are the screenshot:
Git Bash
![1](https://user-images.githubusercontent.com/37857176/38405286-c09bed0a-39a1-11e8-84d7-939856410865.PNG)

CMD
![2](https://user-images.githubusercontent.com/37857176/38405323-dbd55250-39a1-11e8-894c-fb0c0fdfd118.PNG)

It worked normally when I run from python.
![4](https://user-images.githubusercontent.com/37857176/38405351-ff5ee7d6-39a1-11e8-99e4-fe9945ea99ae.PNG)

**Comment by daniel-kukiela** [comment]
Ok, thank you.
I think that your problem might actually be space character in folder name (`New folder`). Could you please either remove space or replace it with underscore for example and let me know if that helped?

**Comment by daniel-kukiela** [comment]
In case you wonder - this should be fixed now (with latest version of code)
