### ISSUE TITLE
prepare_for_deployment.py

### ISSUE THREAD

**Issue by Reckhouse** [daniel-kukiela/nmt-chatbot#54]
When I launch the prepare_for_deployment.py script I am getting the following.
``
`paperspace@pseoih0j5:~/Desktop/nmt_chatbot/utils$ python prepare_for_deployment.py
Traceback (most recent call last):
  File "prepare_for_deployment.py", line 9, in <module>
    from setup.settings import hparams, preprocessing
ModuleNotFoundError: No module named 'setup'
``

When I move the script to the nmt_chatbot folder I get "There are no model checkpoints ready for deployment'.

Am I missing something obvious?

**Comment by daniel-kukiela** [comment]
Did you modify this file in any way?
Line 9 contains `import colorama`, not what's in your Traceback.
Can you show first 10 lines from that script?

**Comment by Reckhouse** [comment]
First 10 lines of the prepare_for_deployment.py script is

``import os
os.chdir(os.path.realpath(os.path.dirname(os.path.dirname(__file__))))
import sys
sys.path.insert(0, os.getcwd())
import errno
import shutil
import time
import colorama
from setup.settings import hparams, preprocessing


colorama.init()``

**Comment by daniel-kukiela** [comment]
This file is modified, it's not in form that's in our repo: https://github.com/daniel-kukiela/nmt-chatbot/blob/master/utils/prepare_for_deployment.py
Did you modify other files and/or data/folder stucture?
Is there `setup` folder "one level up"?
You were able to run `prepare_data.py` that is using the same imports, i'm not sure what's your problem here.

**Comment by Reckhouse** [comment]
I am sorry.  Most have messed everything up when i was moving model folder around.

**Comment by daniel-kukiela** [comment]
You don't have to sorry :) I hope you were able to solve your issue.
