### ISSUE TITLE
Should I continue training after train loss increase?

### ISSUE THREAD

**Issue by mcnoob88** [daniel-kukiela/nmt-chatbot#55]
My train loss suddenly increase during the 2nd epoch when I am training my 3.2 million pairs data. Should I continue training or retrain a new model? I am using the auto decay learn rate.

**Comment by Sentdex** [comment]
Maybe. Depends by how much it increased, for how long, and ho far along in training you are.

**Comment by mcnoob88** [comment]
I have been training for 2 days. But now the train_loss seems to drop.
Here is my chart.
![6](https://user-images.githubusercontent.com/37857176/38457463-29a320c6-3ac3-11e8-9bea-6d726e69f042.PNG)
