### ISSUE TITLE
Does the number of pairs (training data) impacts the step duration ? 

### ISSUE THREAD

**Issue by tolotrasamuel** [daniel-kukiela/nmt-chatbot#56]
I run train.py for the first time with 3 * GeForce GTX 1060 6G and I get on average 12 seconds per step on a training size of 120,000 pairs. 
I am planning to increase the training pairs to 2 millions. Will my duration per step decrease? 
Is there a way to calculate the duration of step based on the training pairs?

**Comment by daniel-kukiela** [comment]
12 seconds per step is a pretty big value, are you sure you're doing that training using GPU(s)? You should have `tensorflow-gpu` installed, not `tensorflow`.
Also, to utilize all 3 GPUs (won't give you much speed improvement tho) add `num_gpus = 3` into `hparams` section of `setup/settings.py`

Your duration per step will not change when you increase number of paird in training set. Overall training time will increase. You can calculate how many steps do you need to train for a full epoch by dividing number of pairs by `batch_size` (128 by default). Also with newer version of code you'll be informed about that (green messages).

**Comment by tolotrasamuel** [comment]
I tried to put **num_gpus = 3** in **hparams** as a propriety for the dictionary. However, I noticed that only 2 gpu are being used 
![image](https://user-images.githubusercontent.com/29230303/38577096-005e049c-3d11-11e8-8046-a7ca3805569e.png)
As you can one the screenshot above, the 3rd GPU is not used at all. GPU0 is used at around 60% on average and GPU1 is at 100%. 
Why aren't all of them used at 100% ? I made sure however to set  **num_gpus = 3**

**Comment by daniel-kukiela** [comment]
As far as i know, NMT places different layers on different GPUs. If you are using only 2 layers, that might explain it.
By NMT i mean https://github.com/tensorflow/nmt - we are including that in our project. If you want to know more about how to utilize multiple GPUs, it's better to ask there. If you are going to do that, please point me to that topic, so i could learned as well how exactly it's done.
