### ISSUE TITLE
FileNotFound Error in prepare_data.py

### ISSUE THREAD

**Issue by sahand100** [daniel-kukiela/nmt-chatbot#60]
[log.txt](https://github.com/daniel-kukiela/nmt-chatbot/files/1898129/log.txt)
hi, when i run prepare_data.py errors in log file appears.
i noticed this line:

> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Sahand\\Desktop\\nmt-chatbot\\prepare_data.py
it tries to find prepare_data.py in root directory but it's in setup.
Windows 10 x64 ( Anaconda / tf 1.7.0 )

**Comment by daniel-kukiela** [comment]
Are you using latest version of code?
I fixed that issue about 5 days ago.
I would like to confirm that latest version of code works like expected.

**Comment by daniel-kukiela** [comment]
Thank you for explanation (outside of GitHub). That should be fixed by latest commits.
