### ISSUE TITLE
Unreliable chatbot reply

### ISSUE THREAD

**Issue by mcnoob88** [daniel-kukiela/nmt-chatbot#61]
I have just finished training my 3.2million pairs chatbot but the reply from the chatbot is not really reliable. Should I continue training it or retrain a new model?

**Comment by daniel-kukiela** [comment]
What do you exactly mean by "finished training"?

**Comment by daniel-kukiela** [comment]
I'm not sure how to answer. It depends on training data, also 4 epochs might me not enough. There is no single simple answer to that question.

**Comment by daniel-kukiela** [comment]
It is not possible with live inference - live inference is for testing purposes. You can embed our chatbot in own code and write own printing function to print only best scored answer. You'll find very simple example in README.

**Comment by mcnoob88** [comment]
Ok thks. I will check it out.

**Comment by mcnoob88** [comment]
@daniel-kukiela it will be pretty nice if you can provide a sample code to print the best scored answer from embed chatbot. I don't really know how to do it since I just started python a few month earlier. Can you please just write a simple one so I can get a hang of it?

**Comment by ArtemSer** [comment]
It is in the README. Just run `python interference.py`, type a message and hit `enter`. Or if you want to get data in the code you can do smth like this
```
from nmt_chatbot.inference import inference

print(inference("Hello NMT"))
```
it will give you 

- answers - a list of all answers
- scores - list of scores for answers
- best_index - index of the best answer
- best_score - score of the best answer

Amount of replies you can define in `setup/settings.py`. 
Also for empty question function will return `none`.
