### ISSUE TITLE
"regex" module

### ISSUE THREAD

**Issue by ghost** [daniel-kukiela/nmt-chatbot#62]
Traceback (most recent call last):
  File "setup/prepare_data.py", line 5, in <module>
    from core.tokenizer import tokenize
  File "C:\Users\TS\Documents\chatbotmath\mathchatbot1\core\tokenizer.py", line 2, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'

I installed the requirements in the requirements text file. Does anyone know how to get regex?

Thanks for the help.

**Comment by daniel-kukiela** [comment]
Sorry for late reply, i was very busy last time.
Do you have that issue still?

**Comment by UmutAlihan** [comment]
Hi, I still have this issue


Traceback (most recent call last):
  File "prepare_data.py", line 8, in <module>
    from core.tokenizer import tokenize
  File "../core/tokenizer.py", line 2, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'

**Comment by kobrata6** [comment]
> Hi, I still have this issue
> 
> Traceback (most recent call last):
> File "prepare_data.py", line 8, in
> from core.tokenizer import tokenize
> File "../core/tokenizer.py", line 2, in
> import regex as re
> ModuleNotFoundError: No module named 'regex'

Use only  "import re"
Thats how I fixed my problem

**Comment by UmutAlihan** [comment]
thanks solved it!
