### ISSUE TITLE
Stuck at Shuffle buffer filled 

### ISSUE THREAD

**Issue by VioletViolence** [daniel-kukiela/nmt-chatbot#63]
When i run train.py it goes to the point of filling shuffle buffer right before the start of actual training and nothing comes up after. It keeps using 90% of my CPU (i run CPU version) though.

CPU -- two Intel Xeons 2.46 GHz 8 physical cores on each. 

Should i wait more? (i've left it for a few hours in this state and nothing's changed)

Update: works fine now. I've just left it and overnight all worked out somehow. I get 8-10s per step though, so maybe that was just a performance issue

**Comment by daniel-kukiela** [comment]
Few hours is way to long. It's not a chatbot problem probably tho, and i didn;t see behaviour like that earlier.
Try to reinstall TensorFlow Maybe

**Comment by UmutAlihan** [comment]
I have the same issue :/

**Comment by brendanartley** [comment]
I have been having exactly the same issue as well
