### ISSUE TITLE
Can we use this repo without a GPU ??

### ISSUE THREAD

**Issue by MicrocontrollersAndMore** [daniel-kukiela/nmt-chatbot#64]
Following the readme, if we do the `pip install -r requirements.txt` line, the first line of requirements.txt is `tensorflow-gpu>=1.4.0`, but what if we don't have a GPU?  Can we simply edit this to `tensorflow>=1.4.0` before running the `pip install -r requirements.txt` command?

Upon a quick search and skimming of this repo I can't seem to find any content that would require a GPU, however I'll admit I certainly haven't read every line.

Has anybody tried this on a computer without a GPU?  Is it even possible?  Are there substantial edits involved or just the one I'm guessing noted above?

For anybody that has administrative access to this repo issue list please mark this as a question, I'd to it myself but apparently I don't have the necessary permissions.

**Comment by VioletViolence** [comment]
Yes, you totaly can run it on CPU only. I run it on the GPU-less server.

It will be slow though. Considerably slower than on GPU. I'm using two intel Xeons with 8 cores on each an it's taking AGES to train.

**Comment by daniel-kukiela** [comment]
On a pretty decent PC, training on CPU is about ~20x slower than using GPU. You also should gave good amount of RAM for (8 GB, but training is possible when you have 4 GB as well).

**Comment by KodeyThomas** [comment]
It would take a while to get the same results so 10 hours work turns into 50 hours
