### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by EpicShardGamingYT** [daniel-kukiela/nmt-chatbot#67]
i get this error when i try 2 run the train.py script:
`
Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.`

**Comment by mapingshuo** [comment]
I think your tensorflow is not installed properly. You can try to google this ERROR firstly.

**Comment by daniel-kukiela** [comment]
How did you install tensorflow? hat version of python are you using and how did you install it?
