### ISSUE TITLE
when i run the train.py i get the following error

### ISSUE THREAD

**Issue by jaiaravind4u** [daniel-kukiela/nmt-chatbot#68]
`tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
         [[Node: dynamic_seq2seq/decoder/embedding_lookup/_61 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_50_dynamic_seq2seq/decoder/embedding_lookup", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]`

**Comment by daniel-kukiela** [comment]
Is it a full error message?
What version of Python and TensorFlow are you using?
