### ISSUE TITLE
Allocation of 1098299904 exceeds 10% of system memory.

### ISSUE THREAD

**Issue by TheChair** [daniel-kukiela/nmt-chatbot#69]
Whenever I run train.py, after "# Init train iterator, skipping 0 elements" this message keeps appearing: Allocation of [number] exceeds 10% of system memory.
Does anyone know how to fix this?

My specs are:
     CPU: I7 4790
     GPU: GTX 1050ti 4GB VRAM
     RAM: 12 GB
My settings.py is:
https://pastebin.com/uC3TQsU5

**Comment by daniel-kukiela** [comment]
Did you change anything in code?
Are you using `tensorflow-gpu`?

**Comment by TheChair** [comment]
Sorry, I ended up fixing it myself after a while. Both on CPU and GPU the issue was occuring.

I turned 'override_loaded_hparams' to True and the batch down to 100, and everything worked fine. I'd assume it was 'override_loaded_hparams' because I tried with just batch size and that didn't work.

Thanks!
