### ISSUE TITLE
IndexError : list index out of range

### ISSUE THREAD

**Issue by umangkr** [daniel-kukiela/nmt-chatbot#7]
![screenshot 2](https://user-images.githubusercontent.com/30562064/33610852-90bd4e80-d9f2-11e7-8cb4-3b96e005ceb8.png)

I have attached the screenshot above..

**Comment by daniel-kukiela** [comment]
Did you modify training files? It looks like number of lines in your tst2012 and/or tst2013 files between "from" and "to" files doesn't match. You have to have pairs, and that means number of lines in tst2012.from file must match number of lines in tst2012.to. Same for tst2013.(from|to).
Doublecheck that please.

**Comment by umangkr** [comment]
okay i'll recheck that.
can you tell me what vocab size should i use? my gpu has 2gb vram.

**Comment by daniel-kukiela** [comment]
With 2GB of VRAM try to lower 'num_units' to 256 and leave vocab as is.
If you get OOM error try to lower vocab by 2k, and try again. You can change 'vocab_size' in settings and run prepare_data.py again.
If you are doing any changes in hparams section of settings, remember to either set 'override_loaded_hparams' or remove everything inside 'model' folder (as settings are saved within model after first run of train.py).

**Comment by umangkr** [comment]
no no i am not doing any changes in anything.. 
i just ran it in default settings and this index error keeps coming up.

**Comment by daniel-kukiela** [comment]
So do a clean clone, change 'num_units' to 256 and do everything step by step once more.

**Comment by umangkr** [comment]
okay brother.
i'll do that and let you know.
