### ISSUE TITLE
Zero blue score at the 1st epoch

### ISSUE THREAD

**Issue by phongnhhn92** [daniel-kukiela/nmt-chatbot#72]
Hello guys, I am trying to build my own chat bot using the reddit data (2017-11).
I am training my model but I found that the blue score is 0 after 17000 steps. I also check the bot reply and it seems like most of the answer is "I am not sure and I dont know". Is that a normal thing ? 

  step 15100 lr 0.001 step-time 3.09s wps 2.21K ppl 70.33 gN 7.78 bleu 0.00, Sat Jun 30 18:33:38 2018
  step 15200 lr 0.001 step-time 3.10s wps 2.26K ppl 71.30 gN 6.99 bleu 0.00, Sat Jun 30 18:38:48 2018
  step 15300 lr 0.001 step-time 3.17s wps 2.20K ppl 71.09 gN 8.19 bleu 0.00, Sat Jun 30 18:44:05 2018
  step 15400 lr 0.001 step-time 3.16s wps 2.22K ppl 69.52 gN 8.40 bleu 0.00, Sat Jun 30 18:49:21 2018
  step 15500 lr 0.001 step-time 3.34s wps 2.08K ppl 70.32 gN 8.90 bleu 0.00, Sat Jun 30 18:54:55 2018
  step 15600 lr 0.001 step-time 3.29s wps 2.13K ppl 69.34 gN 8.17 bleu 0.00, Sat Jun 30 19:00:24 2018
  step 15700 lr 0.001 step-time 3.29s wps 2.14K ppl 69.62 gN 8.38 bleu 0.00, Sat Jun 30 19:05:53 2018
  step 15800 lr 0.001 step-time 3.22s wps 2.18K ppl 69.37 gN 7.90 bleu 0.00, Sat Jun 30 19:11:15 2018
  step 15900 lr 0.001 step-time 3.21s wps 2.17K ppl 68.51 gN 8.34 bleu 0.00, Sat Jun 30 19:16:36 2018
  step 16000 lr 0.001 step-time 3.24s wps 2.15K ppl 68.27 gN 9.71 bleu 0.00, Sat Jun 30 19:22:00 2018

Should I keep training or not ?

**Comment by mapingshuo** [comment]
I think this is normal, maybe this issue helpful:  #66

**Comment by mapingshuo** [comment]
Yes, bleu is not so important, You can read this paper: "BLEU: a Method for Automatic Evaluation of Machine Translation", it is very easy to understand.

**Comment by daniel-kukiela** [comment]
And also very hard to write any score that will tell you if response is coherent or not. That's why we don;t have any, and to be honest BLEU should probably be removed.

Speaking of responses: https://github.com/daniel-kukiela/nmt-chatbot/issues/77
