### ISSUE TITLE
What are the "tst" files and why are they required ?

### ISSUE THREAD

**Issue by shubhank008** [daniel-kukiela/nmt-chatbot#75]
I was following sentdex's tutorial and my prepared sample data only has train.from/to and test.from/to while the nmt-chatbot requires additional tst2012 and tst2013 files.  
New to tensorflow and ML in general, can someone please tell me whats going on, why those files are needed and if I can just copy and rename my test.from/to files to those files instead.

**Comment by mapingshuo** [comment]
tst2012 is a validation data and tst2013 is a test data. you can split some of your train data to validation and test data.

**Comment by daniel-kukiela** [comment]
You can just use the same files (test.*) as tst2012.* and 2013.*. They can consist of identical sentences. I'm going to remove one of them later, as it's not necessary, and maybe rename remaining one just to test.*

**Comment by shubhank008** [comment]
@mapingshuo @daniel-kukiela thanks, I did figure out the same taking look at the provided sample data and copied my test.to/from files and renamed them instead. Was kind of confusing at was using NMT for first time. 
And yep, renaming that to test.* would be more self-explanatory :P
