### ISSUE TITLE
How to add audio output for the chatbot's response? 

### ISSUE THREAD

**Issue by tiancaipipi110** [daniel-kukiela/nmt-chatbot#78]
Well, this is not an issue more of a question. 
How to add audio output for the chatbot's response? Thanks.

**Comment by daniel-kukiela** [comment]
I'm not sure if you joined our Discord (https://discord.gg/sGMngU) and heard our chatbots there, but if yes, it's our own implementation of TTS.

As far as i know people are often using gTTS, as it provides the best voice quality,
