### ISSUE TITLE
Any way to fit a large data set ( 17M samples ) in low VRAM ( 4 GB ) ?

### ISSUE THREAD

**Issue by kunwar31** [daniel-kukiela/nmt-chatbot#8]
![image](https://user-images.githubusercontent.com/24824080/33611629-15da82b6-d9f5-11e7-80ed-126383dd266e.png)

For the sample data provided, the maximum vocab size I could use was 15175. But for my own data set, that won't work. The shape of the tensor it wants to allocate is changed somehow. For the sample data it was something like [20000,vocab_size] and now it's much bigger [124288,vocab_size]. How exactly can I reduce that number? I tried vocab size of 12500 but even that won't fit and I don't want to go any lower than that. Any help would be great.

I'm using a GTX 960M with 4GB VRam on windows 10.  Data I'm using contains all comments with score > 5 from months 6-10 of 2017.

**Comment by daniel-kukiela** [comment]
Did you change anything in settings? If yes, did you either uncomment 'override_loaded_hparams' or remove everything inside 'model' folder? hparams section from settings is saved with model after first train.py run.

**Comment by kunwar31** [comment]
Everytime I change my settings I remove everything inside 'model' folder and re-run prepare_data.py ( if changed vocab_size )

**Comment by kunwar31** [comment]
Okay I see that num_units is directly proportional to that, so I can reduce that number somehow and fit it. Should I be doing more epochs then If I go with a very low num_units value?

**Comment by daniel-kukiela** [comment]
One more question at the moment - did you clone that repo at it's current state or are you using your fork made at some point? There were a bug associated with training set creation.

**Comment by daniel-kukiela** [comment]
With 4GB of VRAM you should probably use defaults. I was training models in my GTX 970 with 4GB of VRAM with that settings (but with slightly bigger vocab of size of 17k tokens).

**Comment by kunwar31** [comment]
I cloned it a few days back... 3 Dec I guess. The problem with defaults is that it won't work on my data set but works on sample data set. Does size of each line matter as well? for example, If all comments are less than , let's say, 1000 characters, would it help reduce how much memory is required?
How many training samples did you use in your data set?

**Comment by Sentdex** [comment]
We haven't yet made a setting for it, but the other integral item with VRAM usage while training is the batch size. ATM, batch size is 128, and it could be 64 or even 32 and still produce decent results. Maybe we should also expose batch_size in settings.py.

**Comment by daniel-kukiela** [comment]
I fixed that bug on Decemeber 3rd, so please do a fresh clone and try again.

**Comment by kunwar31** [comment]
@daniel-kukiela I'll do that and try again. Thank you :)
@Sentdex Thank you for the tip, I'll try using different batch_size(s).BTW, your videos are awesome :)

**Comment by kunwar31** [comment]
@daniel-kukiela @Sentdex I tried both of the things at the same time and lowering batch_size works, also that about that bug, I no longer need to remove empty lines from vocab manually. Thank you for help.
Also, I've made a pull request #9 for adding batch_size in settings.py
