### ISSUE TITLE
[Suggestion] Separate model location path as a argument

### ISSUE THREAD

**Issue by shubhank008** [daniel-kukiela/nmt-chatbot#81]
Separating the model's location as a command line argument or as a parameter for inference() method would be really cool and allow remote hosting of the model files (S3 buckets).  

I had been playing around trying to make my trained model work on AWS Lambda as it seems perfect option for a hosted solution for deployment compared to a EC2 but due to its nature and size limits, the model needs to be saved and loaded from a S3 bucket and as such, would need a way to change location/path of the model to load from S3 or supply the path as argument.  

I know it might not make sense as a needed feature, but if you can hint me at the lines I need to change in inference.py to load the model from a S3 bucket, I can probably try it out myself and heck even contribute Lambda deployment guide.  

PS: I think the model is being loaded at line #98, but cannot figure out the lines its being read as physical path or as such. 
The very few tuts/articles I could find create and use/load the graph from model (.pb) files instead of full model

PS: Are you folks running your deployment on CPU only servers ? I benchmarked a few EC2 instances and the bot response time was 7-11 seconds (it was 5~ secs on my Ryzen 2700x with GTX1070 PC).

**Comment by daniel-kukiela** [comment]
Hmmm, i didn't have any plans to do that.
Everything what;s configurable sits in setup/settings.py. `out_dir` is probably what you are looking for.

Yes, we are running models on CPU only. It takes just copuple of seconds on some bigger instance in DigitalOcean. On my slamm DO vps it takes even up to 30 seconds to make a response.

**Comment by daniel-kukiela** [comment]
I did't really try to change model directory after training, so i'm not sure if that will work. If it won't, let me know - i'll look at that.
Problematic part might be hparams file created by nmt (not our code).
