### ISSUE TITLE
How to setup inference to output one answer with the highest score?

### ISSUE THREAD

**Issue by stas4000** [daniel-kukiela/nmt-chatbot#82]
Hi,
Couldn't find anywhere in issues a question of this kind nor a clear instruction in README.
So my question is how do I setup my trained bot to give me a single answer selected by the maximum score.

Also, I would love to know if there is a setting that filters links (I mean always returns a response without a website link)

Thanks in advance.

**Comment by frameworkapi** [comment]
i tried coding for single but couldn't. if any one has done so please let me know

**Comment by daniel-kukiela** [comment]
This project is prepared mainly for importing. There is inference script, but mostly for testing purposes. Make own project, place nmt-chatbot inside it, and import (like in README). Then print output - you'll see all responses and index of best scored response.

Currently there's no way to filter all links out. You will have to modify scoring code.

**Comment by stas4000** [comment]
Thanks for your response, I already modified the inference.py script so that now I'm getting one response with the highest score that is not a link.

**Comment by frameworkapi** [comment]
hello,
i would like to know how did you remove link outputs.
thanks.

**Comment by daniel-kukiela** [comment]
Best way to rmove llinks is to filter them out from a training dataset, otherwise all answers might be a links for a question.

**Comment by stas4000** [comment]
Hi Frameworkapi,

Daniel is correct the best way is indeed to remove all links from dataset, but if you already trained your model and you'd like to filter the links there is a way using regex.

I am attaching my customized inference.py file.
It's filtering all links and outputs a single answer with the highest score.
Just look below line 307

[inference.zip](https://github.com/daniel-kukiela/nmt-chatbot/files/2238293/inference.zip)

For clarification I filtered the answers with this regex: "https?://(?:[-\w.]|(?:%[\da-fA-F]{2}))+"
