### ISSUE TITLE
Context  with Tensorflow

### ISSUE THREAD

**Issue by nipun03** [daniel-kukiela/nmt-chatbot#84]
Hi Daniel. I have a question. Will it be possible to implement tensorflow with context? Or can you guide me how it can be done?
Example. **You:** Who is the president of US?   **Bot:** Donald Trump is the president of US
**You:** What is his height?     **Bot:** He(Trump) is 5.7 inch
Something like this.

**Comment by nipun03** [comment]
Okay. So it is possible to have context with seq2seq model (nmt). Which files do I need to modify in order to have context flow with the chat bot?

**Comment by daniel-kukiela** [comment]
I don't know answer to both questions, sorry.

**Comment by nipun03** [comment]
No problem, Daniel.
